version: 2.1

commands:
  install_dependencies:
    parameters:
      compilers:
        type: string
        default: ""
    steps:
      - run: 
          name: Install dependencies
          command: |
            apt-get update
            apt-get --assume-yes install cmake
            apt-get --assume-yes install << parameters.compilers >>

  build_project:
    parameters:
      compiler:
        type: string
        default: ""
    steps:
      - run: 
          name: Build project with << parameters.compiler >>
          command: |
            export CXX=<< parameters.compiler >>
            mkdir build_debug
            mkdir build_release
            cd build_debug
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${CXX} ..
            cmake --build .
            cd ../build_release
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${CXX} .. 
            cmake --build .

jobs:
  Ubuntu-14-04:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - install_dependencies:
          compilers: g++-4.7 g++-4.8
      - build_project:
          compiler: g++-4.7
      - build_project:
          compiler: g++-4.8

  Ubuntu-16-04:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - install_dependencies:
          compilers: g++-4.7 g++-4.8 g++-4.9 g++-5
      - build_project:
          compiler: g++-4.7
      - build_project:
          compiler: g++-4.8
      - build_project:
          compiler: g++-4.9
      - build_project:
          compiler: g++-5

  Ubuntu-18-04:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - install_dependencies:
          compilers: g++-4.8 g++-5 g++-6 g++-7 g++-8
      - build_project:
          compiler: g++-4.8
      - build_project:
          compiler: g++-5
      - build_project:
          compiler: g++-6
      - build_project:
          compiler: g++-7
      - build_project:
          compiler: g++-8

  Ubuntu-20-04:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - install_dependencies:
          compilers: g++-7 g++-8 g++-9 g++-10
      - build_project:
          compiler: g++-7
      - build_project:
          compiler: g++-8
      - build_project:
          compiler: g++-9
      - build_project:
          compiler: g++-10

  Ubuntu-21-04:
    docker:
      - image: ubuntu:21.04
    steps:
      - checkout
      - install_dependencies:
          compilers: g++-7 g++-8 g++-9 g++-10 g++-11
      - build_project:
          compiler: g++-7
      - build_project:
          compiler: g++-8
      - build_project:
          compiler: g++-9
      - build_project:
          compiler: g++-10
      - build_project:
          compiler: g++-11

workflows:
  version: 2
  workflow:
    jobs:
      #- Ubuntu-14-04
      - Ubuntu-16-04
      - Ubuntu-18-04
      - Ubuntu-20-04
      - Ubuntu-21-04